#!/bin/bash
module="hellfire"
device="hellfire"
mode="777"

insmod ../core/$module.ko || exit 1
# get Major number dynamically
major=$(awk -vmodule="$module" '$0 ~ module {print $1;}' /proc/devices)
mknod /dev/${device} c "$major" 0
chmod $mode /dev/${device}
